apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tasky.fullname" . }}-secrets
  namespace: {{ .Values.environment }}
  labels:
    {{- include "tasky.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: {{ .Values.config.mongodbUri | quote }}
