apiVersion: v1
kind: Service
metadata:
  name: tasky-service
  namespace: tasky-app
  labels:
    app: tasky-app
spec:
  type: LoadBalancer
  selector:
    app: tasky-app
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  sessionAffinity: None
