apiVersion: v2
name: tasky
description: A Helm chart for Tasky App - Task Management Application
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - tasky
  - tasks
  - todo
  - mongodb
maintainers:
  - name: Tasky Team
home: https://github.com/blueprints2009/tasky-app
